### ISSUE TITLE
unexpected ')' on Ruby 2.7

### ISSUE THREAD

**Issue by MarioRuiz** [socketry/console#37]
```
SyntaxError:
  /home/travis/.rvm/gems/ruby-2.7.1/gems/console-1.16.2/lib/console/progress.rb:77: syntax error, unexpected ')'
  			@output.info(@subject, ...)
  			                          ^
  /home/travis/.rvm/gems/ruby-2.7.1/gems/console-1.16.2/lib/console/progress.rb:106: syntax error, unexpected end-of-input, expecting `end'
# /home/travis/.rvm/gems/ruby-2.7.1/gems/console-1.16.2/lib/console/logger.rb:10:in `require_relative'
# /home/travis/.rvm/gems/ruby-2.7.1/gems/console-1.16.2/lib/console/logger.rb:10:in `<top (required)>'
# /home/travis/.rvm/gems/ruby-2.7.1/gems/console-1.16.2/lib/console.rb:10:in `require_relative'
# /home/travis/.rvm/gems/ruby-2.7.1/gems/console-1.16.2/lib/console.rb:10:in `<top (required)>'
# /home/travis/.rvm/gems/ruby-2.7.1/gems/async-1.30.3/lib/async/logger.rb:23:in `require'
# /home/travis/.rvm/gems/ruby-2.7.1/gems/async-1.30.3/lib/async/logger.rb:23:in `<top (required)>'
# /home/travis/.rvm/gems/ruby-2.7.1/gems/async-1.30.3/lib/async.rb:24:in `require_relative'
# /home/travis/.rvm/gems/ruby-2.7.1/gems/async-1.30.3/lib/async.rb:24:in `<top (required)>'
```

**Comment by ioquatix** [comment]
This is causing a fair amount of problems, so let me check how easy it is to restore compatibility.

**Comment by ioquatix** [comment]
I would personally suggest updating to 2.7.6 too, which will fix this issue.

**Comment by ioquatix** [comment]
Okay, after trying it out, the best solution by far is for you to update to Ruby 2.7.3+.
