### ISSUE TITLE
NoMethodError · undefined method `[]' for #Console::Buffer

### ISSUE THREAD

**Issue by mperham** [socketry/console#4]
I can't parse this Bugsnag issue but maybe you'll grok it:

```
Caused by: gems/console-1.2.2/lib/console/event/failure.rb:57:in `format_exception': undefined method `[]' for #<Console::Buffer:0x000056035520ec58> (NoMethodError)
    from gems/console-1.2.2/lib/console/event/failure.rb:73:in `format_exception'
    from gems/console-1.2.2/lib/console/event/failure.rb:51:in `format'
    from gems/console-1.2.2/lib/console/terminal/logger.rb:109:in `format_argument'
    from gems/console-1.2.2/lib/console/terminal/logger.rb:95:in `call'
    from gems/console-1.2.2/lib/console/filter.rb:116:in `call'
    from gems/console-1.2.2/lib/console/filter.rb:41:in `block (3 levels) in []'
    from gems/async-1.17.1/lib/async/task.rb:189:in `fail!'
    from gems/async-1.17.1/lib/async/task.rb:210:in `rescue in block in make_fiber'
    from gems/async-1.17.1/lib/async/task.rb:204:in `block in make_fiber'

Caused by: gems/async-dns-1.2.2/lib/async/dns/handler.rb:63:in `rescue in process_query': undefined method `log_exception' for Async::DNS:Module (NoMethodError)
    from gems/async-dns-1.2.2/lib/async/dns/handler.rb:57:in `process_query'
    from gems/async-dns-1.2.2/lib/async/dns/handler.rb:83:in `respond'
    from gems/async-dns-1.2.2/lib/async/dns/handler.rb:77:in `block in run'
    from gems/async-1.17.1/lib/async/task.rb:204:in `block in make_fiber'
```

**Comment by ioquatix** [comment]
Ah, yeah, I can fix that.

**Comment by ioquatix** [comment]
Can you try this out and let me know if your issue is resolved?

**Comment by mperham** [comment]
Isn't the problem with this call to []: `terminal[:exception_title]`?  How do your changes fix it?

**Comment by ioquatix** [comment]
@mperham due to a cut and paste error, there was something very weird going on with the argument handling, especially the optional `prefix = nil`. Because of that, the wrong things were ending up in the wrong positions when dealing with nested exceptions. I wrote a spec for it and it failed, but with the changes it now passes.
